# Generated by Django 2.2.6 on 2019-10-18 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mods', '0002_auto_20191018_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('1', 'Combat'), ('2', 'Building'), ('3', 'Other')], default='Other', max_length=1),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=20000),
        ),
    ]
