# Generated by Django 2.2.6 on 2019-10-18 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mods', '0003_auto_20191018_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default='image1.jpg', upload_to='thumbnails'),
        ),
    ]
