# Generated by Django 2.2.6 on 2019-10-18 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mods', '0004_post_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('1', 'Combat'), ('2', 'Food'), ('3', 'Storage'), ('4', 'Magic'), ('5', 'World Gen'), ('6', 'API and Library'), ('7', 'Mobs and Creatures'), ('8', 'Armor, Tools and Weapons'), ('9', 'Cosmetic'), ('10', 'Technology'), ('11', 'Miscellaneous'), ('12', 'Other')], default='Other', max_length=1),
        ),
    ]
