# Generated by Django 2.2.6 on 2019-10-19 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mods', '0005_auto_20191019_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
