# Generated by Django 2.2.6 on 2019-10-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mods', '0006_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(default='Click for informations', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='download_1',
            field=models.CharField(default='www.google.de', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='download_1_version',
            field=models.CharField(choices=[('0', '1.15'), ('1', '1.14.4'), ('2', '1.14'), ('3', '1.13.2'), ('4', '1.12.2'), ('5', '1.11.2'), ('6', '1.10.2'), ('7', '1.9.4'), ('8', '1.8.9'), ('9', '1.7.10'), ('10', '1.7.2'), ('11', '1.6.4'), ('12', 'Other (Description)')], default='1.12.2', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='download_2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='download_2_version',
            field=models.CharField(blank=True, choices=[('0', '1.15'), ('1', '1.14.4'), ('2', '1.14'), ('3', '1.13.2'), ('4', '1.12.2'), ('5', '1.11.2'), ('6', '1.10.2'), ('7', '1.9.4'), ('8', '1.8.9'), ('9', '1.7.10'), ('10', '1.7.2'), ('11', '1.6.4'), ('12', 'Other (Description)')], max_length=1),
        ),
        migrations.AddField(
            model_name='post',
            name='download_3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='download_3_version',
            field=models.CharField(blank=True, choices=[('0', '1.15'), ('1', '1.14.4'), ('2', '1.14'), ('3', '1.13.2'), ('4', '1.12.2'), ('5', '1.11.2'), ('6', '1.10.2'), ('7', '1.9.4'), ('8', '1.8.9'), ('9', '1.7.10'), ('10', '1.7.2'), ('11', '1.6.4'), ('12', 'Other (Description)')], max_length=1),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(upload_to='thumbnails'),
        ),
    ]
