# Generated by Django 2.2.6 on 2019-10-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mods', '0007_auto_20191020_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(max_length=80),
        ),
    ]
