# Generated by Django 2.2.6 on 2019-11-02 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mods', '0010_auto_20191020_2027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='download_1',
            new_name='download',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='download_1_version',
            new_name='version',
        ),
        migrations.RemoveField(
            model_name='post',
            name='download_2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='download_2_version',
        ),
        migrations.RemoveField(
            model_name='post',
            name='download_3',
        ),
        migrations.RemoveField(
            model_name='post',
            name='download_3_version',
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('1', 'Combat'), ('2', 'Food'), ('3', 'Storage'), ('4', 'Magic'), ('5', 'World Gen'), ('6', 'API and Library'), ('7', 'Mobs and Creatures'), ('8', 'Armor, Tools and Weapons'), ('9', 'Cosmetic'), ('10', 'Technology'), ('11', 'Miscellaneous'), ('12', 'Other')], default='Other', max_length=2),
        ),
    ]
