# Generated by Django 2.2.6 on 2019-11-02 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mods', '0011_auto_20191102_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='website',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
