# Generated by Django 2.2.6 on 2019-11-02 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mods', '0012_post_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='download',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='version',
            field=models.CharField(choices=[('0', '1.15'), ('1', '1.14.4'), ('2', '1.14'), ('3', '1.13.2'), ('4', '1.12.2'), ('5', '1.11.2'), ('6', '1.10.2'), ('7', '1.9.4'), ('8', '1.8.9'), ('9', '1.7.10'), ('10', '1.7.2'), ('11', '1.6.4'), ('12', 'Other (Description)')], max_length=2),
        ),
        migrations.AlterField(
            model_name='post',
            name='website',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
